version: '2.3'
services:
  proxy:
    image: nginx:latest
    container_name: proxyserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    depends_on:
      - frontend

  frontend:
    build:
      ../stage1/app/
    image: flask-app:latest
    ports:
      - 5000
    environment:
      - VIRTUAL_HOST=factorial
    depends_on:
      - redis
    cpu_percent: 5

  redis:
    image: redis:latest
    build:
      ../stage1/redis_db
    volumes:
      - /var/cec:/data
    ports:
      - 6379:6379
    container_name: redisdb